import { useState } from "react";
import { router } from "expo-router";
import { KeyboardAvoidingView,Platform,Pressable,StyleSheet,Text,TextInput } from "react-native";
import { createRoom } from "../lib/insync";

export default function Create(){
 const [name,setName]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 async function submit(){try{setBusy(true);setError("");const n=name.trim()||"Host";const room=await createRoom(n);router.replace({pathname:"/room/[code]",params:{code:room.code,name:n}})}catch(e){setError(e instanceof Error?e.message:"Could not create room. Check your connection and try again.")}finally{setBusy(false)}}
 return <KeyboardAvoidingView behavior={Platform.OS==="ios"?"padding":undefined} style={s.page}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Back</Text></Pressable><Text style={s.kicker}>START A ROOM</Text><Text style={s.title}>Your private watch room.</Text><Text style={s.copy}>Choose a display name. We’ll make a private eight-character code for your partner.</Text><TextInput placeholder="Your name" placeholderTextColor="#717c92" value={name} onChangeText={setName} maxLength={80} autoCorrect={false} returnKeyType="done" onSubmitEditing={submit} style={s.input} accessibilityLabel="Your display name"/><Pressable disabled={busy} onPress={submit} style={[s.button,busy&&s.disabled]}><Text style={s.buttonText}>{busy?"Creating room…":"Create private room"}</Text></Pressable>{error?<Text style={s.error}>{error}</Text>:null}<Text style={s.note}>Only someone with your invite code can join.</Text></KeyboardAvoidingView>
}
const s=StyleSheet.create({page:{flex:1,padding:28,paddingTop:58,gap:16,backgroundColor:"#090e1b"},back:{color:"#9aa8ff",fontSize:17,fontWeight:"700",marginBottom:24},kicker:{color:"#8da2fb",fontWeight:"900",letterSpacing:2,fontSize:12},title:{color:"white",fontSize:36,lineHeight:41,fontWeight:"900"},copy:{color:"#aeb7cc",fontSize:16,lineHeight:24,marginBottom:10},input:{backgroundColor:"#151c30",borderWidth:1,borderColor:"#29324b",borderRadius:15,padding:17,color:"white",fontSize:17},button:{backgroundColor:"#7c8cff",borderRadius:15,padding:17,marginTop:4},disabled:{opacity:.55},buttonText:{textAlign:"center",fontWeight:"900",fontSize:17,color:"#08101f"},error:{color:"#ffadb9",lineHeight:20},note:{color:"#687287",fontSize:12,textAlign:"center",marginTop:6}});
