import { useState } from "react";
import { router } from "expo-router";
import { KeyboardAvoidingView,Platform,Pressable,StyleSheet,Text,TextInput } from "react-native";
import { getRoom } from "../lib/insync";

export default function Join(){
 const [code,setCode]=useState("");const [name,setName]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 async function submit(){if(code.length!==8||busy)return;try{setBusy(true);setError("");await getRoom(code);router.replace({pathname:"/room/[code]",params:{code,name:name.trim()||"Guest"}})}catch{setError("We couldn't find that room. Check the code and try again.")}finally{setBusy(false)}}
 return <KeyboardAvoidingView behavior={Platform.OS==="ios"?"padding":undefined} style={s.page}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Back</Text></Pressable><Text style={s.kicker}>JOIN YOUR PERSON</Text><Text style={s.title}>Enter their room.</Text><Text style={s.copy}>Type the private eight-character code they shared with you.</Text><TextInput placeholder="ROOM CODE" placeholderTextColor="#717c92" value={code} onChangeText={x=>{setError("");setCode(x.toUpperCase().replace(/[^A-Z2-9]/g,"").slice(0,8))}} autoCapitalize="characters" autoCorrect={false} maxLength={8} style={[s.input,s.code]} accessibilityLabel="Room code"/><TextInput placeholder="Your name" placeholderTextColor="#717c92" value={name} onChangeText={setName} maxLength={80} autoCorrect={false} returnKeyType="go" onSubmitEditing={submit} style={s.input} accessibilityLabel="Your display name"/><Pressable disabled={code.length!==8||busy} onPress={submit} style={[s.button,(code.length!==8||busy)&&s.disabled]}><Text style={s.buttonText}>{busy?"Finding room…":"Join room"}</Text></Pressable>{error?<Text style={s.error}>{error}</Text>:null}</KeyboardAvoidingView>
}
const s=StyleSheet.create({page:{flex:1,padding:28,paddingTop:58,gap:16,backgroundColor:"#090e1b"},back:{color:"#9aa8ff",fontSize:17,fontWeight:"700",marginBottom:24},kicker:{color:"#8da2fb",fontWeight:"900",letterSpacing:2,fontSize:12},title:{color:"white",fontSize:36,lineHeight:41,fontWeight:"900"},copy:{color:"#aeb7cc",fontSize:16,lineHeight:24,marginBottom:10},input:{backgroundColor:"#151c30",borderWidth:1,borderColor:"#29324b",borderRadius:15,padding:17,color:"white",fontSize:17},code:{fontSize:22,fontWeight:"900",letterSpacing:4,textAlign:"center"},button:{backgroundColor:"#7c8cff",borderRadius:15,padding:17,marginTop:4},disabled:{opacity:.4},buttonText:{textAlign:"center",fontWeight:"900",fontSize:17,color:"#08101f"},error:{color:"#ffadb9",lineHeight:20}});
