import { HubConnection, HubConnectionBuilder, HttpTransportType, LogLevel } from "@microsoft/signalr";
export type Participant={id:string;name:string;ready:boolean;online:boolean};
export type ContentSelection={title:string;provider:string;url?:string};
export type Playback={position:number;playing:boolean;sequence:number;updatedAt:string};
export type Room={code:string;participants:Participant[];content?:string;selection?:ContentSelection;playback:Playback;ended:boolean};
export type RoomEvents={onPlayback?:(s:Playback)=>void;onParticipant?:(p:Participant)=>void;onParticipantLeft?:(p:Participant)=>void;onReady?:(id:string,ready:boolean)=>void;onContent?:(content:string)=>void;onMedia?:(selection:ContentSelection)=>void;onReaction?:(emoji:string)=>void;onEnded?:()=>void};
export function expectedPlaybackPosition(p:Playback,now=Date.now()){const updated=Date.parse(p.updatedAt);if(!p.playing||!Number.isFinite(updated))return Math.max(0,p.position);return Math.max(0,p.position+Math.max(0,(now-updated)/1000));}
const configuredApiUrl=process.env.EXPO_PUBLIC_API_URL?.trim();
if(!configuredApiUrl&&!__DEV__)throw new Error("EXPO_PUBLIC_API_URL is required for production builds.");
const baseUrl=(configuredApiUrl??"http://localhost:5000").replace(/\/$/,"");
if(!__DEV__&&!baseUrl.startsWith("https://"))throw new Error("Production InSync API must use HTTPS.");
export async function createRoom(name:string):Promise<Room>{const r=await fetch(`${baseUrl}/api/rooms`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name})});if(!r.ok)throw new Error("Could not create room.");return r.json();}
export async function getRoom(code:string):Promise<Room>{const r=await fetch(`${baseUrl}/api/rooms/${code}`);if(!r.ok)throw new Error("Room not found.");return r.json();}
export async function connectToRoom(code:string,name:string,e:RoomEvents={}):Promise<HubConnection>{const c=new HubConnectionBuilder().withUrl(`${baseUrl}/hubs/rooms`,{transport:HttpTransportType.LongPolling,skipNegotiation:false}).configureLogging(LogLevel.Critical).withAutomaticReconnect([0,1000,2000,5000,10000]).build();c.serverTimeoutInMilliseconds=120000;c.keepAliveIntervalInMilliseconds=15000;if(e.onPlayback)c.on("PlaybackChanged",e.onPlayback);if(e.onParticipant)c.on("ParticipantJoined",e.onParticipant);if(e.onParticipantLeft)c.on("ParticipantLeft",e.onParticipantLeft);if(e.onReady)c.on("ParticipantReady",e.onReady);if(e.onContent)c.on("ContentSelected",e.onContent);if(e.onMedia)c.on("MediaSelected",e.onMedia);if(e.onReaction)c.on("ReactionSet",e.onReaction);if(e.onEnded)c.on("RoomEnded",e.onEnded);c.onreconnected(async()=>{try{await c.invoke("JoinRoom",code,name)}catch{}});await c.start();await c.invoke("JoinRoom",code,name);return c;}