import { useEffect,useRef,useState } from "react";
import { useLocalSearchParams } from "expo-router";
import { Pressable,ScrollView,StyleSheet,Text,TextInput,View } from "react-native";
import type { HubConnection } from "@microsoft/signalr";
import { connectToRoom,getRoom,Participant,Playback } from "../../lib/insync";
import YouTubeSyncPlayer,{youtubeVideoId} from "../../components/YouTubeSyncPlayer";

export default function RoomScreen(){
 const p=useLocalSearchParams<{code:string;name:string}>();const code=String(p.code);const name=String(p.name??"Guest");const conn=useRef<HubConnection|null>(null);
 const [status,setStatus]=useState("Connecting…"),[error,setError]=useState(""),[playback,setPlayback]=useState<Playback>({position:0,playing:false,sequence:0,updatedAt:""}),[people,setPeople]=useState<Participant[]>([]),[mediaUrl,setMediaUrl]=useState(""),[draftUrl,setDraftUrl]=useState(""),[reaction,setReaction]=useState(""),[playerReady,setPlayerReady]=useState(false),[joined,setJoined]=useState(false);
 useEffect(()=>{let active=true;getRoom(code).then(r=>{if(active){setPeople(r.participants);setMediaUrl(r.selection?.url??"");setDraftUrl(r.selection?.url??"");setPlayback(r.playback)}}).catch(()=>{});
 const reconcile=setInterval(()=>{getRoom(code).then(r=>{if(!active)return;setPeople(r.participants);if(r.selection?.url){setMediaUrl(r.selection.url);setDraftUrl(v=>youtubeVideoId(v)?v:r.selection?.url??v)}setPlayback(v=>r.playback.sequence>v.sequence?r.playback:v)}).catch(()=>{})},3000);
 connectToRoom(code,name,{onPlayback:x=>{if(active)setPlayback(x)},onParticipant:x=>active&&setPeople(v=>v.some(y=>y.id===x.id)?v.map(y=>y.id===x.id?x:y):[...v,x]),onParticipantLeft:x=>active&&setPeople(v=>v.map(y=>y.id===x.id?x:y)),onMedia:x=>active&&(setPlayerReady(false),setMediaUrl(x.url??""),setDraftUrl(x.url??"")),onReaction:x=>{if(active){setReaction(x);setTimeout(()=>setReaction(""),1600)}},onEnded:()=>active&&setStatus("Room ended")}).then(c=>{if(active){conn.current=c;setJoined(true);c.onreconnecting(()=>{if(active){setJoined(false);setStatus("Reconnecting…")}});c.onreconnected(async()=>{if(!active)return;setJoined(true);setStatus("Connected");try{const r=await getRoom(code);setPeople(r.participants);setMediaUrl(r.selection?.url??"");setDraftUrl(r.selection?.url??"");setPlayback(r.playback)}catch{}});c.onclose(()=>{if(active){setJoined(false);setStatus("Disconnected")}});setStatus("Connected")}else c.stop()}).catch(()=>setStatus("Connection failed"));
 return()=>{active=false;clearInterval(reconcile);conn.current?.stop()}},[code,name]);
 useEffect(()=>{const url=draftUrl.trim();if(!joined||!youtubeVideoId(url)||url===mediaUrl)return;const timer=setTimeout(async()=>{try{if(!conn.current||conn.current.state!=="Connected")return;setError("");await conn.current.invoke("SelectMedia",code,{title:"YouTube video",provider:"youtube",url});}catch(e){setError(e instanceof Error?e.message:"Could not load video.")}},450);return()=>clearTimeout(timer)},[draftUrl,mediaUrl,joined,code]);
 const currentPosition=()=>playback.playing?Math.max(0,playback.position+Math.max(0,(Date.now()-Date.parse(playback.updatedAt))/1000)):playback.position;
 const invoke=async(method:string,...args:any[])=>{setError("");try{if(!conn.current||conn.current.state!=="Connected")throw new Error("Still connecting. Try again in a moment.");await conn.current.invoke(method,code,...args)}catch(e){setError(e instanceof Error?e.message:"Something went wrong.")}};
 return <ScrollView contentContainerStyle={s.page}><View style={s.row}><View><Text style={s.kicker}>PRIVATE ROOM</Text><Text style={s.title}>{code}</Text></View><View style={s.status}><Text style={s.statusText}>● {status}</Text></View></View>
 {error?<View style={s.errorBox}><Text style={s.errorText}>{error}</Text></View>:null}<View style={s.card}><Text style={s.label}>Together now</Text>{people.map(x=><Text key={x.id} style={s.person}>{!x.online?"◌":"●"}  {x.name}{!x.online?" · offline":""}</Text>)}<Text style={s.hint}>Share code {code} with your partner.</Text></View>
 <View style={s.card}><Text style={s.label}>What are you watching?</Text><TextInput placeholder="Paste a YouTube link" placeholderTextColor="#707b94" value={draftUrl} onChangeText={x=>{setPlayerReady(false);setDraftUrl(x)}} autoCapitalize="none" autoCorrect={false} style={s.input}/><Text style={s.hint}>{youtubeVideoId(draftUrl)?"Video detected — syncing to both phones…":"Paste a YouTube link and InSync will load it on both phones."}</Text></View>
 {mediaUrl&&youtubeVideoId(mediaUrl)?<View style={s.card}><Text style={s.label}>Watch together</Text><Text style={s.hint}>{playerReady?"Video ready — press Play on either phone to watch in sync.":"Loading video on this phone…"}</Text><YouTubeSyncPlayer url={mediaUrl} playback={playback} onReady={()=>setPlayerReady(true)} onPlayerError={code=>setError(code===-1?"Your phone blocked automatic playback. Tap the video player once, then press Play again.":`YouTube could not embed this video (error ${code}). Try another public, embeddable video.`)} onLocalPlayback={(position,playing)=>invoke("PlaybackChanged",position,playing)}/></View>:null}
 <View style={s.card}><Text style={s.label}>Sync controls</Text><Text style={s.now}>{playback.playing?"▶ Playing":"Ⅱ Paused"} · {formatTime(playback.position)}</Text><View style={s.timeline}><View style={[s.progress,{width:`${Math.min(100,(playback.position/7200)*100)}%`}]} /></View><View style={s.controls}><Pressable style={s.control} onPress={()=>invoke("PlaybackChanged",currentPosition(),!playback.playing)}><Text style={s.controlText}>{playback.playing?"Pause":"Play"}</Text></Pressable><Pressable style={s.control} onPress={()=>invoke("PlaybackChanged",Math.max(0,currentPosition()-10),playback.playing)}><Text style={s.controlText}>−10s</Text></Pressable><Pressable style={s.control} onPress={()=>invoke("PlaybackChanged",currentPosition()+10,playback.playing)}><Text style={s.controlText}>+10s</Text></Pressable></View></View>
 <View style={s.card}><Text style={s.label}>React together</Text><View style={s.controls}>{["❤️","😂","😮","👏"].map(x=><Pressable key={x} style={s.emoji} onPress={()=>invoke("React",x)}><Text style={s.emojiText}>{x}</Text></Pressable>)}</View>{reaction?<Text style={s.reaction}>{reaction}</Text>:null}</View>
 </ScrollView>
}
function formatTime(seconds:number){const total=Math.max(0,Math.round(seconds));const h=Math.floor(total/3600),m=Math.floor((total%3600)/60),s=total%60;return h?`${h}:${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`:`${m}:${String(s).padStart(2,"0")}`}
const s=StyleSheet.create({page:{padding:24,paddingTop:54,paddingBottom:60,gap:16,backgroundColor:"#0b1020"},row:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},kicker:{color:"#8da2fb",fontWeight:"800",letterSpacing:2},title:{color:"white",fontSize:36,fontWeight:"800"},status:{backgroundColor:"#15251e",paddingHorizontal:12,paddingVertical:8,borderRadius:99},statusText:{color:"#80d6a1",fontWeight:"700"},card:{backgroundColor:"#151c30",padding:18,borderRadius:18,gap:12},label:{color:"#aeb7cc",fontWeight:"700"},person:{color:"white",fontSize:17},hint:{color:"#778199"},input:{backgroundColor:"#0e1425",borderRadius:12,padding:14,color:"white",borderWidth:1,borderColor:"#29324b"},now:{color:"white",fontSize:22,fontWeight:"800"},controls:{flexDirection:"row",gap:10,flexWrap:"wrap"},control:{backgroundColor:"#7c8cff",paddingVertical:13,paddingHorizontal:18,borderRadius:12},controlText:{fontWeight:"800",color:"#08101f"},emoji:{backgroundColor:"#0e1425",padding:13,borderRadius:14},timeline:{height:7,backgroundColor:"#29324b",borderRadius:99,overflow:"hidden"},progress:{height:"100%",backgroundColor:"#7c8cff"},emojiText:{fontSize:24},reaction:{fontSize:42,textAlign:"center"},errorBox:{backgroundColor:"#3a1f28",padding:12,borderRadius:12},errorText:{color:"#ffb4c2",fontWeight:"700"}});