import { useEffect,useRef,useState } from "react";
import { useLocalSearchParams } from "expo-router";
import { Pressable,ScrollView,StyleSheet,Text,TextInput,View } from "react-native";
import type { HubConnection } from "@microsoft/signalr";
import { connectToRoom,getRoom,Participant,Playback } from "../../lib/insync";

export default function RoomScreen(){
 const p=useLocalSearchParams<{code:string;name:string}>();const code=String(p.code);const name=String(p.name??"Guest");const conn=useRef<HubConnection|null>(null);
 const [status,setStatus]=useState("Connecting…"),[playback,setPlayback]=useState<Playback>({position:0,playing:false,sequence:0,updatedAt:""}),[people,setPeople]=useState<Participant[]>([]),[content,setContent]=useState(""),[draft,setDraft]=useState(""),[reaction,setReaction]=useState(""),[ready,setReady]=useState(false),[seek,setSeek]=useState(0);
 useEffect(()=>{let active=true;getRoom(code).then(r=>{if(active){setPeople(r.participants);setContent(r.content??"");setDraft(r.content??"");setPlayback(r.playback)}}).catch(()=>{});
 connectToRoom(code,name,{onPlayback:x=>{if(active){setPlayback(x);setSeek(x.position)}},onParticipant:x=>active&&setPeople(v=>v.some(y=>y.id===x.id)?v.map(y=>y.id===x.id?x:y):[...v,x]),onParticipantLeft:x=>active&&setPeople(v=>v.map(y=>y.id===x.id?x:y)),onReady:(id,ready)=>active&&setPeople(v=>v.map(x=>x.id===id?{...x,ready}:x)),onContent:x=>active&&(setContent(x),setDraft(x)),onReaction:x=>{if(active){setReaction(x);setTimeout(()=>setReaction(""),1600)}},onEnded:()=>active&&setStatus("Room ended")}).then(c=>{if(active){conn.current=c;setStatus("Connected")}else c.stop()}).catch(()=>setStatus("Connection failed"));
 return()=>{active=false;conn.current?.stop()}},[code,name]);
 const invoke=(method:string,...args:any[])=>conn.current?.invoke(method,code,...args);
 return <ScrollView contentContainerStyle={s.page}><View style={s.row}><View><Text style={s.kicker}>PRIVATE ROOM</Text><Text style={s.title}>{code}</Text></View><View style={s.status}><Text style={s.statusText}>● {status}</Text></View></View>
 <View style={s.card}><Text style={s.label}>Together now</Text>{people.map(x=><Text key={x.id} style={s.person}>{!x.online?"◌":x.ready?"✓":"○"}  {x.name}{!x.online?" · offline":""}</Text>)}<Text style={s.hint}>Share code {code} with your partner.</Text></View>
 <View style={s.card}><Text style={s.label}>Ready for date night?</Text><Text style={s.hint}>Mark yourself ready when you have your streaming app or video open.</Text><Pressable style={[s.readyButton,ready&&s.readyOn]} onPress={()=>{const next=!ready;setReady(next);invoke("SetReady",name,next)}}><Text style={s.readyText}>{ready?"✓ I’m ready":"I’m ready"}</Text></Pressable></View>
 <View style={s.card}><Text style={s.label}>What are you watching?</Text><TextInput placeholder="Movie, show, YouTube video…" placeholderTextColor="#707b94" value={draft} onChangeText={setDraft} style={s.input}/><Pressable style={s.smallButton} onPress={()=>invoke("SelectContent",draft.trim())}><Text style={s.smallText}>Share selection</Text></Pressable>{content?<Text style={s.selection}>Tonight: {content}</Text>:null}</View>
 <View style={s.card}><Text style={s.label}>Sync controls</Text><Text style={s.now}>{playback.playing?"▶ Playing":"Ⅱ Paused"} · {formatTime(playback.position)}</Text><View style={s.timeline}><View style={[s.progress,{width:`${Math.min(100,(playback.position/7200)*100)}%`}]} /></View><View style={s.controls}><Pressable style={s.control} onPress={()=>invoke("PlaybackChanged",playback.position,!playback.playing)}><Text style={s.controlText}>{playback.playing?"Pause":"Play"}</Text></Pressable><Pressable style={s.control} onPress={()=>invoke("PlaybackChanged",Math.max(0,playback.position-10),playback.playing)}><Text style={s.controlText}>−10s</Text></Pressable><Pressable style={s.control} onPress={()=>invoke("PlaybackChanged",playback.position+10,playback.playing)}><Text style={s.controlText}>+10s</Text></Pressable></View></View>
 <View style={s.card}><Text style={s.label}>React together</Text><View style={s.controls}>{["❤️","😂","😮","👏"].map(x=><Pressable key={x} style={s.emoji} onPress={()=>invoke("React",x)}><Text style={s.emojiText}>{x}</Text></Pressable>)}</View>{reaction?<Text style={s.reaction}>{reaction}</Text>:null}</View>
 </ScrollView>
}
function formatTime(seconds:number){const total=Math.max(0,Math.round(seconds));const h=Math.floor(total/3600),m=Math.floor((total%3600)/60),s=total%60;return h?`${h}:${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`:`${m}:${String(s).padStart(2,"0")}`}
const s=StyleSheet.create({page:{padding:24,paddingTop:54,paddingBottom:60,gap:16,backgroundColor:"#0b1020"},row:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},kicker:{color:"#8da2fb",fontWeight:"800",letterSpacing:2},title:{color:"white",fontSize:36,fontWeight:"800"},status:{backgroundColor:"#15251e",paddingHorizontal:12,paddingVertical:8,borderRadius:99},statusText:{color:"#80d6a1",fontWeight:"700"},card:{backgroundColor:"#151c30",padding:18,borderRadius:18,gap:12},label:{color:"#aeb7cc",fontWeight:"700"},person:{color:"white",fontSize:17},hint:{color:"#778199"},input:{backgroundColor:"#0e1425",borderRadius:12,padding:14,color:"white",borderWidth:1,borderColor:"#29324b"},smallButton:{backgroundColor:"#293452",padding:13,borderRadius:12},smallText:{color:"white",textAlign:"center",fontWeight:"700"},selection:{color:"#cdd3ff"},now:{color:"white",fontSize:22,fontWeight:"800"},controls:{flexDirection:"row",gap:10,flexWrap:"wrap"},control:{backgroundColor:"#7c8cff",paddingVertical:13,paddingHorizontal:18,borderRadius:12},controlText:{fontWeight:"800",color:"#08101f"},emoji:{backgroundColor:"#0e1425",padding:13,borderRadius:14},timeline:{height:7,backgroundColor:"#29324b",borderRadius:99,overflow:"hidden"},progress:{height:"100%",backgroundColor:"#7c8cff"},emojiText:{fontSize:24},reaction:{fontSize:42,textAlign:"center"},readyButton:{backgroundColor:"#293452",padding:14,borderRadius:12},readyOn:{backgroundColor:"#2d6a4f"},readyText:{color:"white",textAlign:"center",fontWeight:"800"}});