import { useEffect,useRef,useState } from "react";
import { router,useLocalSearchParams } from "expo-router";
import { Pressable,ScrollView,Share,StyleSheet,Text,TextInput,View } from "react-native";
import type { HubConnection } from "@microsoft/signalr";
import { connectToRoom,getRoom,Participant,Playback } from "../../lib/insync";
import YouTubeSyncPlayer,{youtubeVideoId} from "../../components/YouTubeSyncPlayer";

export default function RoomScreen(){
 const p=useLocalSearchParams<{code:string;name:string}>();const code=String(p.code);const name=String(p.name??"Guest");const conn=useRef<HubConnection|null>(null);
 const [status,setStatus]=useState("Connecting…"),[error,setError]=useState(""),[playback,setPlayback]=useState<Playback>({position:0,playing:false,sequence:0,updatedAt:""}),[people,setPeople]=useState<Participant[]>([]),[mediaUrl,setMediaUrl]=useState(""),[draftUrl,setDraftUrl]=useState(""),[reaction,setReaction]=useState(""),[playerReady,setPlayerReady]=useState(false),[joined,setJoined]=useState(false);
 useEffect(()=>{let active=true;getRoom(code).then(r=>{if(active){setPeople(r.participants);setMediaUrl(r.selection?.url??"");setDraftUrl(r.selection?.url??"");setPlayback(r.playback)}}).catch(()=>{});
 const reconcile=setInterval(()=>{getRoom(code).then(r=>{if(!active)return;setPeople(r.participants);if(r.selection?.url){setMediaUrl(r.selection.url);setDraftUrl(v=>youtubeVideoId(v)?v:r.selection?.url??v)}setPlayback(v=>r.playback.sequence>v.sequence?r.playback:v)}).catch(()=>{})},3000);
 connectToRoom(code,name,{onPlayback:x=>active&&setPlayback(x),onParticipant:x=>active&&setPeople(v=>v.some(y=>y.id===x.id)?v.map(y=>y.id===x.id?x:y):[...v,x]),onParticipantLeft:x=>active&&setPeople(v=>v.map(y=>y.id===x.id?x:y)),onMedia:x=>active&&(setPlayerReady(false),setMediaUrl(x.url??""),setDraftUrl(x.url??"")),onReaction:x=>{if(active){setReaction(x);setTimeout(()=>setReaction(""),1600)}},onEnded:()=>active&&setStatus("Room ended")}).then(c=>{if(active){conn.current=c;setJoined(true);c.onreconnecting(()=>{if(active){setJoined(false);setStatus("Reconnecting…")}});c.onreconnected(async()=>{if(!active)return;setJoined(true);setStatus("Connected");try{const r=await getRoom(code);setPeople(r.participants);setMediaUrl(r.selection?.url??"");setDraftUrl(r.selection?.url??"");setPlayback(r.playback)}catch{}});c.onclose(()=>{if(active){setJoined(false);setStatus("Disconnected")}});setStatus("Connected")}else c.stop()}).catch(()=>setStatus("Connection failed"));
 return()=>{active=false;clearInterval(reconcile);conn.current?.stop()}},[code,name]);
 useEffect(()=>{const url=draftUrl.trim();if(!joined||!youtubeVideoId(url)||url===mediaUrl)return;const timer=setTimeout(async()=>{try{if(!conn.current||conn.current.state!=="Connected")return;setError("");await conn.current.invoke("SelectMedia",code,{title:"YouTube video",provider:"youtube",url});}catch(e){setError(e instanceof Error?e.message:"Could not load video.")}},450);return()=>clearTimeout(timer)},[draftUrl,mediaUrl,joined,code]);
 const invoke=async(method:string,...args:any[])=>{setError("");try{if(!conn.current||conn.current.state!=="Connected")throw new Error("Still connecting. Try again in a moment.");await conn.current.invoke(method,code,...args)}catch(e){setError(e instanceof Error?e.message:"Something went wrong.")}};
 const shareInvite=()=>Share.share({message:`Join my private InSync room. Room code: ${code}`}).catch(()=>{});
 const leave=async()=>{try{await conn.current?.stop()}finally{router.replace("/")}};
 const online=people.filter(x=>x.online);
 const partner=online.find(x=>x.name!==name)??online[1];
 const connected=status==="Connected";
 return <ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled">
  <View style={s.header}><View><Text style={s.brand}>INSYNC</Text><Text style={s.room}>Room {code}</Text></View><View style={[s.status,!connected&&s.statusWarn]}><Text style={[s.statusText,!connected&&s.statusWarnText]}>● {status}</Text></View></View>
  {error?<View style={s.errorBox}><Text style={s.errorText}>{error}</Text></View>:null}
  <View style={s.people}><Text style={s.peopleText}>● {name}</Text><Text style={partner?s.peopleText:s.waiting}>{partner?`● ${partner.name}`:"◌ Waiting for your partner"}</Text></View>
  {!partner?<Pressable style={s.invite} onPress={shareInvite} accessibilityRole="button" accessibilityLabel="Invite partner"><Text style={s.inviteText}>Invite Partner</Text><Text style={s.inviteSub}>Share private code {code}</Text></Pressable>:null}
  <View style={s.watchCard}>
   <Text style={s.label}>WATCH TOGETHER</Text>
   <TextInput placeholder="Paste a YouTube link" placeholderTextColor="#707b94" value={draftUrl} onChangeText={x=>{setPlayerReady(false);setDraftUrl(x)}} autoCapitalize="none" autoCorrect={false} keyboardType="url" style={s.input} accessibilityLabel="YouTube link"/>
   {!mediaUrl?<Text style={s.hint}>Paste a YouTube link. It will load automatically for both of you.</Text>:null}
   {mediaUrl&&youtubeVideoId(mediaUrl)?<View style={s.playerWrap}><YouTubeSyncPlayer url={mediaUrl} playback={playback} onReady={()=>setPlayerReady(true)} onPlayerError={c=>setError(c===-1?"Tap the video once, then press Play again.":`YouTube could not play this video (error ${c}). Try another public video.`)} onLocalPlayback={(position,playing)=>invoke("PlaybackChanged",position,playing)}/>{reaction?<View pointerEvents="none" style={s.reactionBubble}><Text style={s.reaction}>{reaction}</Text></View>:null}</View>:null}
   {mediaUrl?<Text style={s.sync}>{connected?(playerReady?(playback.playing?"● Synced · Watching together":"● Synced · Ready to play"):"● Synced · Loading video…"):"◌ Reconnecting…"}</Text>:null}
  </View>
  <View style={s.reactions}><Text style={s.label}>REACT</Text><View style={s.emojiRow}>{["❤️","😂","😮","👏","🔥"].map(x=><Pressable key={x} style={s.emoji} onPress={()=>invoke("React",x)} accessibilityRole="button" accessibilityLabel={`Send ${x} reaction`}><Text style={s.emojiText}>{x}</Text></Pressable>)}</View></View>
  <View style={s.actions}><Pressable style={s.shareButton} onPress={shareInvite}><Text style={s.shareText}>Share Invite</Text></Pressable><Pressable style={s.leaveButton} onPress={leave}><Text style={s.leaveText}>Leave Room</Text></Pressable></View>
  <Text style={s.footer}>Playback is controlled directly from the video and stays synced between both phones.</Text>
 </ScrollView>
}
const s=StyleSheet.create({page:{padding:22,paddingTop:54,paddingBottom:48,gap:16,backgroundColor:"#090e1b",minHeight:"100%"},header:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},brand:{color:"#8da2fb",fontWeight:"900",letterSpacing:3,fontSize:13},room:{color:"white",fontSize:20,fontWeight:"800",marginTop:4},status:{backgroundColor:"#14271f",paddingHorizontal:11,paddingVertical:7,borderRadius:99},statusWarn:{backgroundColor:"#302817"},statusText:{color:"#82dca5",fontWeight:"800",fontSize:12},statusWarnText:{color:"#f3c76f"},people:{flexDirection:"row",gap:14,flexWrap:"wrap",paddingVertical:4},peopleText:{color:"#dce3f3",fontWeight:"700"},waiting:{color:"#7d879d"},invite:{backgroundColor:"#7c8cff",padding:16,borderRadius:16,alignItems:"center"},inviteText:{color:"#08101f",fontWeight:"900",fontSize:17},inviteSub:{color:"#202a54",fontWeight:"700",fontSize:12,marginTop:3},watchCard:{backgroundColor:"#141b2d",padding:16,borderRadius:20,gap:12},label:{color:"#8d98af",fontWeight:"900",fontSize:12,letterSpacing:1.4},input:{backgroundColor:"#0c1221",borderRadius:13,padding:14,color:"white",borderWidth:1,borderColor:"#283149",fontSize:15},hint:{color:"#7f899f",lineHeight:20},playerWrap:{position:"relative",overflow:"hidden",borderRadius:14,backgroundColor:"#05070d"},reactionBubble:{position:"absolute",alignSelf:"center",top:"34%",backgroundColor:"rgba(8,12,24,.72)",width:78,height:78,borderRadius:39,alignItems:"center",justifyContent:"center"},reaction:{fontSize:42},sync:{color:"#80d6a1",fontWeight:"800",textAlign:"center",fontSize:13},reactions:{backgroundColor:"#141b2d",padding:16,borderRadius:20,gap:12},emojiRow:{flexDirection:"row",justifyContent:"space-between",gap:8},emoji:{flex:1,minWidth:48,backgroundColor:"#0c1221",paddingVertical:12,borderRadius:14,alignItems:"center"},emojiText:{fontSize:24},actions:{flexDirection:"row",gap:10},shareButton:{flex:1,backgroundColor:"#202942",padding:14,borderRadius:14,alignItems:"center"},shareText:{color:"white",fontWeight:"800"},leaveButton:{flex:1,borderWidth:1,borderColor:"#52303a",padding:14,borderRadius:14,alignItems:"center"},leaveText:{color:"#ffadb9",fontWeight:"800"},footer:{color:"#687287",fontSize:12,lineHeight:18,textAlign:"center",paddingHorizontal:12},errorBox:{backgroundColor:"#3a1f28",padding:12,borderRadius:12},errorText:{color:"#ffb4c2",fontWeight:"700"}});
